Web App VM Management System/Web App VM Management System/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using MailKit.Net.Smtp;
using MimeKit;
using Web_App_VM_Management_System.dtos;

namespace Web_App_VM_Management_System.Controllers
{
    public class ContactController : Controller
    {
        [HttpGet]
        public IActionResult Index(string message="",string color="")
        {
            ViewBag.message = message;
            ViewBag.color= color;
            return View();
        }
            [HttpPost]
        public IActionResult Index(EmailDTO emailDTO)
        {

            using (var smtpClient = new SmtpClient())
            {
                smtpClient.Connect("smtp.gmail.com");
                smtpClient.Authenticate("dev.hassan.naseer@gmail.com", "tgaw vzwk yhvw lqlx");

                var message = new MimeMessage();

                message.From.Add(new MailboxAddress("From", "dev.hassan.naseer@gmail.com"));


                message.To.Add(new MailboxAddress("To", $"fahadiqbal.fd14@gmail.com"));


                message.Subject = $"{emailDTO.Subject}";


                var textPart = new TextPart("plain")
                {
                    Text = emailDTO.Message
                };

                // Attach the text part to the message
                message.Body = textPart;

                // You can add more headers if needed
                //message.Headers.Add("X-Custom-Header", "SomeValue");

                smtpClient.Send(message);
                smtpClient.Disconnect(true);


            }
            ViewBag.message = "Message Sent!";
            ViewBag.color = "green";
            return View();
        }
    }
}

Web App VM Management System/Web App VM Management System/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using Web_App_VM_Management_System.AppContext;
using Web_App_VM_Management_System.dtos;
using Web_App_VM_Management_System.Entities;

namespace Web_App_VM_Management_System.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly VMdbContext _dbContext;

        public EmployeeController(VMdbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewBag.vmCount = _dbContext.Products.Where(x => x.StockQuantity > 0).Count();
                ViewBag.invenCount = _dbContext.InventoryItems.Where(x => x.QuantityInStock > 0).Sum(x => x.QuantityInStock);
                ViewBag.catCount = _dbContext.Categories.Count();
                ViewBag.viCount = _dbContext.VendItems.Count();
                List<Product> products = _dbContext.Products.ToList();
                List<MachineSaleDTO> machines = new List<MachineSaleDTO>();
                foreach (var item in products)
                {
                    MachineSaleDTO dTO = new MachineSaleDTO()
                    {
                        Name = item.Name,
                        TotalSale = _dbContext.Sale.Where(s => s.ProductId == item.Id).Sum(s => s.TotalSale)
                    };
                    machines.Add(dTO);
                }
                ViewBag.todaySale = _dbContext.Sale.ToList().OrderBy(x => x.CreatedDate).LastOrDefault()?.TotalSale;
                ViewBag.totalSale = _dbContext.Sale.Sum(s => s.TotalSale);
                ViewBag.ii = _dbContext.InventoryItems.Where(x => x.QuantityInStock > 0).Sum(s => s.Price);
                ViewBag.vmList = products;
                return View(machines);
            }
            // The user is not logged in
            return RedirectToAction("Login", "Account"); // Redirect to a login page or take appropriate action

        }
        public IActionResult EmployeesList(string message = "", string color = "")
        {

            ViewBag.message = message;
            ViewBag.color = color;
            IEnumerable<Employee> employeesList = _dbContext.Employees.ToList();
            return View(employeesList);
        }

        [HttpGet]
        public IActionResult AddEmployee(string message = "", string color = "")
        {
            ViewBag.message = message;
            ViewBag.color = color;
            return View();
        }

        [HttpPost]
        public IActionResult AddEmployee(Employee employee)
        {

            // Perform any necessary validation and processing
            employee.IsPaid = false;
            employee.Status = "Active";
            employee.CreatedDate = DateTime.Now;
            _dbContext.Employees.Add(employee);
            _dbContext.SaveChanges();
            return RedirectToAction("EmployeesList", new { message = "Employee added successfuly!", color = "green" });
        }

        [HttpGet]
        public IActionResult EditEmployee(int id)
        {
            Employee employee = _dbContext.Employees.FirstOrDefault(e => e.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        [HttpPost]
        public IActionResult EditEmployee(Employee editedEmployee)
        {
            Employee originalEmployee = _dbContext.Employees.FirstOrDefault(e => e.Id == editedEmployee.Id);
            if (originalEmployee == null)
            {
                return NotFound();
            }
            // Perform any necessary validation and processing
            originalEmployee.Name = editedEmployee.Name;
            originalEmployee.PhoneNumber = editedEmployee.PhoneNumber;
            originalEmployee.EmailAddress = editedEmployee.EmailAddress;
            originalEmployee.Salary = editedEmployee.Salary;
            originalEmployee.IsPaid = editedEmployee.IsPaid;
            originalEmployee.ModifiedDate = DateTime.Now;

            _dbContext.SaveChanges();
            return Redirect("/Admin/Index");
        }

        [HttpGet]
        public IActionResult DeleteEmployee(int id)
        {
            Employee employeeToDelete = _dbContext.Employees.FirstOrDefault(e => e.Id == id);
            if (employeeToDelete == null)
            {
                return RedirectToAction("EmployeesList", new { message = "Record does not exist!", color = "red" });
            }
            _dbContext.Employees.Remove(employeeToDelete);
            _dbContext.SaveChanges();
            return RedirectToAction("EmployeesList", new { message = "Employee deleted successfuly!", color = "green" });
        }
        [HttpGet]
        public async Task<object> UpdateSalaryStatus(int id, bool isChecked)
        {
            Employee employee = await _dbContext.Employees.FirstOrDefaultAsync(e => e.Id == id);
            employee.IsPaid = isChecked;
            if (employee == null)
            {
                return RedirectToAction("EmployeesList", new { message = "Record does not exist!", color = "red" });
            }
            _dbContext.Employees.Update(employee);
            _dbContext.SaveChanges();
            string status = isChecked ? "Paid" : "Unpaid";
            string color = isChecked ? "green" : "red";
            return RedirectToAction("EmployeesList", new { message = $"Salary status set to {status}!", color = color });
        }


    }
}

Web App VM Management System/Web App VM Management System/Controllers/ProductGridController.cs
using Microsoft.AspNetCore.Mvc;

namespace Web_App_VM_Management_System.Controllers
{
    public class ProductGridController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web App VM Management System/Web App VM Management System/Views/Contact/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <!-- Include Bootstrap CSS from a CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<style>
    .card-header {
        background-color: white;
    }

    .copy {
        font-size: 12px;
        padding: 10px;
        border-top: 1px solid #FFFFFF;
    }

    .footer-middle {
        padding-top: 2em;
        color: white;
    }
    /*SOCİAL İCONS*/

    /* footer social icons */

    ul.social-network {
        list-style: none;
        display: inline;
        margin-left: 0 !important;
        padding: 0;
    }

        ul.social-network li {
            display: inline;
            margin: 0 5px;
        }


    /* footer social icons */

    .social-network a.icoFacebook:hover {
        background-color: #3B5998;
    }

    .social-network a.icoLinkedin:hover {
        background-color: #007bb7;
    }

        .social-network a.icoFacebook:hover i,
        .social-network a.icoLinkedin:hover i {
            color: #fff;
        }

    .social-network a.socialIcon:hover,
    .socialHoverClass {
        color: #44BCDD;
    }

    .social-circle li a {
        display: inline-block;
        position: relative;
        margin: 0 auto 0 auto;
        -moz-border-radius: 50%;
        -webkit-border-radius: 50%;
        border-radius: 50%;
        text-align: center;
        width: 30px;
        height: 30px;
        font-size: 15px;
    }

    ul li a {
        color: grey
    }

        ul li a:hover {
            color: green
        }

    .social-circle li i {
        margin: 0;
        line-height: 30px;
        text-align: center;
    }

    .social-circle li a:hover i,
    .triggeredHover {
        -moz-transform: rotate(360deg);
        -webkit-transform: rotate(360deg);
        -ms--transform: rotate(360deg);
        transform: rotate(360deg);
        -webkit-transition: all 0.2s;
        -moz-transition: all 0.2s;
        -o-transition: all 0.2s;
        -ms-transition: all 0.2s;
        transition: all 0.2s;
    }

    .social-circle i {
        color: #595959;
        -webkit-transition: all 0.8s;
        -moz-transition: all 0.8s;
        -o-transition: all 0.8s;
        -ms-transition: all 0.8s;
        transition: all 0.8s;
    }

    .social-network a {
        background-color: #F9F9F9;
    }

    .jumbotron {
        background-repeat: no-repeat;
        background-image: linear-gradient(to right, red, yellow);
        background-size: contain;
        background-position: right;
        background-color: white;
        ;
        border-radius: 0 !important;
    }

    #bg-img {
        background-image: url('https://img.freepik.com/free-vector/cartoon-vending-machines-collection_52683-73163.jpg?w=996&t=st=1692691656~exp=1692692256~hmac=708a8db0391f6bdd82d8dd43a472b7be15cc2ee881882c8ababd8e81f47c1def');
    }

    .detail-key {
        color: black; /* Blue color for keys */
        font-weight: bold;
    }

    .detail-value {
        color: #28a745; /* Green color for values */
    }

    .float {
        position: fixed;
        width: 60px;
        height: 60px;
        bottom: 40px;
        right: 40px;
        background-color: #25d366;
        color: #FFF;
        border-radius: 50px;
        text-align: center;
        font-size: 30px;
        box-shadow: 2px 2px 3px #999;
        z-index: 100;
    }

    .v-machine {
        width: 50%;
    }

    .inventory {
        width: 108%;
    }

    .salary {
        border-right: 1px solid lightgrey
    }

    .my-float {
        margin-top: 16px;
    }

    .padding {
        padding: 5rem
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
    }

    .test {
        border: 1px solid #d2d2dc;
        border-radius: 11px;
        -webkit-box-shadow: 0px 0px 5px 0px rgb(249, 249, 250);
        -moz-box-shadow: 0px 0px 5px 0px rgba(212,182,212,1);
        box-shadow: 0px 0px 5px 0px rgb(161, 163, 164);
    }

    .card .card-body {
        padding: 1rem 1rem;
    }

    .card-body {
        flex: 1 1 auto;
        padding: 1.25rem
    }

    p {
        font-size: 0.875rem;
        margin-bottom: .5rem;
        line-height: 1.5rem
    }

    h4 {
        line-height: .2 !important;
    }

    .profile {
        margin-top: 16px;
        margin-left: 11px;
    }

    .profile-pic {
        width: 58px;
    }

    .cust-name {
        font-size: 18px;
    }

    .cust-profession {
        font-size: 10px;
    }



    .items {
        width: 90%;
        margin: 0px auto;
        margin-top: 100px;
    }

    .bg-black {
        background-color: black;
    }

    .slick-slide {
        margin: 10px
    }

    .logo {
        margin: auto;
        width: 90px;
        display: flex;
    }
</style>
<body>
    <nav class="navbar navbar-expand-lg navbar-light mt-1">
        <img src="https://img.freepik.com/premium-vector/healthy-vending-machines-food-logo-template_7109-708.jpg?w=2000" class="logo mr-3" />

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="nav-link text-dark">Home</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "ProductGrid")" class="nav-link text-dark">Catalog</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Contact")" class="nav-link text-dark">Contact us</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
            </form>
            @if (User.Identity.IsAuthenticated)
            {
                @if (User.IsInRole("Admin"))
                {
                    <div class="ml-3">
                        <a href="@Url.Action("Index", "Admin")" class="text-black btn btn-success">Dashboard</a>

                        @Html.ActionLink("LogOut", "Logout", "Account", null, new { @class = "btn btn-primary" })
                    </div>
                }
                else
                {
                    <div class="ml-3">
                        <a href="@Url.Action("Index", "Employee")" class="text-black btn btn-success">Dashboard</a>

                        @Html.ActionLink("LogOut", "Logout", "Account", null, new { @class = "btn btn-primary" })
                    </div>
                }
            }
            else
            {
                @*@Html.ActionLink("Register", "Register", "Account", null, new { @class = "btn btn-success ml-2" })*@
                @Html.ActionLink("Login", "Login", "Account", null, new { @class = "btn btn-primary ml-2" })
            }
        </div>
    </nav>
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h1 class="card-title text-success text-center">Contact Us</h1>
                        <span style="color:@ViewBag.color">@ViewBag.message</span>
                        <form action="/Contact/Index" method="Post">
                            <div class="form-group">
                                <label for="subject">Subject:</label>
                                <input type="text" class="form-control" id="subject" name="Subject" required>
                            </div>

                            <div class="form-group">
                                <label for="message">Message:</label>
                                <textarea class="form-control" id="message" name="Message" rows="5" required></textarea>
                            </div>

                            @*<div class="form-group">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control" id="email" name="Email" required>
                            </div>*@

                            <div class="text-center">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="text-center mt-3">
                    <a href="/">Back to Home</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Include Bootstrap JS and jQuery from a CDN -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>